/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ILucideAlertTriangle: typeof import('~icons/lucide/alert-triangle')['default']
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideAward: typeof import('~icons/lucide/award')['default']
    ILucideCalendarDays: typeof import('~icons/lucide/calendar-days')['default']
    ILucideDot: typeof import('~icons/lucide/dot')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideFileSpreadsheet: typeof import('~icons/lucide/file-spreadsheet')['default']
    ILucideFileUp: typeof import('~icons/lucide/file-up')['default']
    ILucideGraduationCap: typeof import('~icons/lucide/graduation-cap')['default']
    ILucideInbox: typeof import('~icons/lucide/inbox')['default']
    ILucideLayoutGrid: typeof import('~icons/lucide/layout-grid')['default']
    ILucideLoader2: typeof import('~icons/lucide/loader2')['default']
    ILucideLogOut: typeof import('~icons/lucide/log-out')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSettings: typeof import('~icons/lucide/settings')['default']
    ILucideShieldCheck: typeof import('~icons/lucide/shield-check')['default']
    ILucideSmartphone: typeof import('~icons/lucide/smartphone')['default']
    ILucideUserCheck: typeof import('~icons/lucide/user-check')['default']
    ILucideUserCog: typeof import('~icons/lucide/user-cog')['default']
    ILucideUsers: typeof import('~icons/lucide/users')['default']
    ILucideUsers2: typeof import('~icons/lucide/users2')['default']
    ILucideUserX: typeof import('~icons/lucide/user-x')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
