/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideAward: typeof import('~icons/lucide/award')['default']
    ILucideCalendar: typeof import('~icons/lucide/calendar')['default']
    ILucideCalendarDays: typeof import('~icons/lucide/calendar-days')['default']
    ILucideCalendarOff: typeof import('~icons/lucide/calendar-off')['default']
    ILucideDot: typeof import('~icons/lucide/dot')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideInbox: typeof import('~icons/lucide/inbox')['default']
    ILucideLoader2: typeof import('~icons/lucide/loader2')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSmartphone: typeof import('~icons/lucide/smartphone')['default']
    ILucideUser: typeof import('~icons/lucide/user')['default']
    ILucideUserCheck: typeof import('~icons/lucide/user-check')['default']
    ILucideUsers: typeof import('~icons/lucide/users')['default']
    ILucideUserX: typeof import('~icons/lucide/user-x')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
